### PR TITLE
[backend] Atomic testings fail for payloads with file when the file name contains special characters

### LINKED ISSUE #3846: Atomic testing - Fails with payload filenames containing special characters
## Description

Atomic tests with “File Drop” or “Executable” payloads fail when the filename contains special characters.

## Environment

1. OS (where OpenBAS server runs): Mac OS 15.6 Chrome
2. OpenBAS version: local 1.18.10; prerelease 1.18.12 ; test 1.18.12
3. OpenBAS client: backend

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a file whose name contains special characters (e.g., `1.Helloéùàèïë.rtf`).  
2. Create a “File Drop” or “Executable” payload using this file.  
3. Launch an Atomic test with the payload created in step 2.

## Expected Output

1. Executed Status : INJECT EXECUTED
2. The injected filename matches the filename in the payload.

## Actual Output

Executed Status : ERROR

Tab EXECUTION -> Execution logs :
ERROR {"stdout":"","stderr":"Internal(\"Filename not found\")","exit_code":-1}

## Screenshots (optional)

Image

### PR DESCRIPTION
**Pull request by EvaE-Filigran**
### Proposed changes

* Pr related to https://github.com/OpenBAS-Platform/implant/pull/76
*

### Testing Instructions

1. Create a file whose name contains special characters (e.g., 1.Helloéùàèïë.rtf).
2. Create a “File Drop” or “Executable” payload using this file.
3. Launch an Atomic test with the payload created in step 2.

### Related issues

* Closes #3846 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-api/src/test/java/io/openbas/rest/DocumentApiTest.java [hunk 1]
```diff
@@ -141,4 +142,30 @@ void givenDocumentShouldFetchRelatedEntities() throws Exception {
       assertThatJson(response).when(IGNORING_ARRAY_ORDER).isEqualTo(relationJson);
     }
   }
+
+  @Test
+  public void encodeDocumentName() {
```
Comment (savacano28) [inline openbas-api/src/test/java/io/openbas/rest/DocumentApiTest.java:147]: Maybe you could create other file for unit tests?
