### PR TITLE
Fix on the instance creation date to send ISO_INSTANT

### LINKED ISSUE #2902: Telemetry service.instance.creation date is not ISO compliant
## Description

Telemetry service.instance.creation date is not ISO compliant

Image

{"type"=>"document_parsing_exception", "reason"=>"[1:537] failed to parse field [service.instance.creation] of type [date] in document with id 'ljCnGZYB6axxckmkYbut'. Preview of field's value: '2025-04-01 09:57:28.60101'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"failed to parse date field [2025-04-01 09:57:28.60101] with format [strict_date_optional_time||epoch_millis]", "caused_by"=>{"type"=>"date_time_parse_exception", "reason"=>"Failed to parse with all enclosed parsers"}}}}}}

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* Fix on the instance creation date to send ISO_INSTANT
*

### Related issues

* Closes #2902 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java [hunk 1]
```diff
@@ -133,12 +137,16 @@ private Resource buildResource() {
         this.settingRepository.findByKey(PLATFORM_INSTANCE.key()).orElse(new Setting());
     Setting instanceCreationDate =
         this.settingRepository.findByKey(PLATFORM_INSTANCE_CREATION.key()).orElse(new Setting());
+    LocalDateTime creationDate = LocalDateTime.now();
+    if(instanceCreationDate.getValue() != null) {
+      creationDate = LocalDateTime.parse(instanceCreationDate.getValue(), DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.nnnnnn"));
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java:142]: niptick
private static final DateTimeFormatter CREATION_DATE_FORMATTER =
    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.nnnnnn");

**Comment by RomuDeuxfois** [comment]
Test 🆗 
image

File: openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java (hunk 1 above)
Comment (Dimfacion) [reply openbas-api/src/main/java/io/openbas/telemetry/OpenTelemetryConfig.java]: Done !

**Review by RomuDeuxfois — APPROVED** [review]
