### PR TITLE
[frontend] Fix bulk actions on sparse selection (#2328)

### LINKED ISSUE #2328: Bottom bar bulk actions in Injects list view do not work reliably with sparse selection
> Selecting sparse records (not select all) and using the bottom tool bar does not update items on all pages, only the currently displayed page. 

 _Originally posted by @antoinemzs in [#2292](https://github.com/OpenBAS-Platform/openbas/issues/2292#issuecomment-2624156062)_

# Reproducing

1. Navigate to simulation (Injects tab) with more than a single page of injects
2. Select some injects on each page (do not nuse the select all checkbox)
3. Do a bulk action from the bottom bar
4. Only items of the currently displayed page are affected by the bulk action

### PR DESCRIPTION
**Pull request by antoinemzs**
### Proposed changes

* Fix bulk actions on sparse selection

### Related issues

* Fix #2328

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openbas-front/src/utils/hooks/useEntityToggle.ts [hunk 1]
```diff
@@ -17,9 +17,12 @@ export interface UseEntityToggle<T> {
   setSelectedElements: (selectedElements: Record<string, T>) => void;
 }
 
-const useEntityToggle = <T extends Record<string, string>>(
+// we don't know the type of every value in an object type passed here
+// nor is it relevant.
+/* eslint-disable @typescript-eslint/no-explicit-any */
```
Comment (antoinemzs) [inline openbas-front/src/utils/hooks/useEntityToggle.ts:22]: to note

**Review by impolitepanda — APPROVED** [review]
