### PR TITLE
[frontend] migrating from jss to emotion with tss-react (#1821)

### LINKED ISSUE #1821: Tags design is broken
## Description

The design of the tags should be like the one of "no tag"
Image

## Reproducible Steps

go to https://testing.obas.staging.filigran.io/admin/payloads?query=cGFnZT0wJnNpemU9MjAmZmlsdGVyR3JvdXBbZmlsdGVyc11bXSZmaWx0ZXJHcm91cCU1Qm1vZGUlNUQ9YW5kJnNvcnRzJTVCMCU1RCU1QnByb3BlcnR5JTVEPXBheWxvYWRfbmFtZSZ0ZXh0U2VhcmNoPXJkcCZrZXk9cGF5bG9hZHM%3D

### PR DESCRIPTION
**Pull request by guillaumejparis**
### Proposed changes

*
*

### Related issues

* Closes #1821
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-front/src/admin/components/common/entreprise_edition/EnterpriseEditionButton.tsx [hunk 1]
```diff
@@ -1,8 +1,7 @@
 import { RocketLaunchOutlined } from '@mui/icons-material';
 import { Button } from '@mui/material';
-import { makeStyles } from '@mui/styles';
-import classNames from 'classnames';
```
Comment (RomuDeuxfois) [inline openbas-front/src/admin/components/common/entreprise_edition/EnterpriseEditionButton.tsx:4]: Can we remove this lib ?

**Review by RomuDeuxfois — APPROVED** [review]
