### PR TITLE
[backend] Handle errors for payloads

### LINKED ISSUE #1897: Error on executable payload not handle correclty
## Description

When I launch an executable file and there are an error in the execution, the inject status is: INJECT EXECUTED.

My payload: 

```
$url = "https://redcanary.com/wp-content/uploads/Atomic-Red-Team-Logo.png"
$imgLocation = "$env:TEMP\T1491.001-newWallpaper.png"
$orgWallpaper = "C:\Users\RomualdLemesle\Pictures\joker-batman-the-dark-knight-heath-ledger-wallpaper-preview.jpg"
$orgWallpaper | Out-File -FilePath "$env:TEMP\T1491.001-OrginalWallpaperLocation"
$updateWallpapercode = @'
using System.Runtime.InteropServices;
namespace Win32{

    public class Wallpaper{
        [DllImport("user32.dll", CharSet=CharSet.Auto)]
         static extern int SystemParametersInfo (int uAction , int uParam , string lpvParam , int fuWinIni) ;
         
         public static void SetWallpaper(string thePath){
            SystemParametersInfo(20,0,thePath,3);
        }
    }
}
'@

$wc = New-Object System.Net.WebClient
try {
    $wc.DownloadFile($url, $imgLocation)

    # Vérifier et ajouter le type si nécessaire
    if (-not ("Win32.Wallpaper" -as [type])) {
        Add-Type -TypeDefinition $updateWallpapercode
    }

    [Win32.Wallpaper]::SetWallpaper($imgLocation)
}
catch [System.Net.WebException] {
    Write-Host("Cannot download $url")

    if (-not ("Win32.Wallpaper" -as [type])) {
        Add-Type -TypeDefinition $updateWallpapercode
    }

    [Win32.Wallpaper]::SetWallpaper($imgLocation)
}
finally {
    $wc.Dispose()
}

```

The result in UI: 
Image

The log: 
```
{"timestamp":"2024-11-20T11:07:31.992308Z","level":"INFO","fields":{"message":"Starting OpenBAS implant 1.8.1 production","log.target":"openbas_implant","log.module_path":"openbas_implant","log.file":"src\\main.rs","log.line":152},"target":"openbas_implant"}
{"timestamp":"2024-11-20T11:07:32.098651Z","level":"INFO","fields":{"message":"file execution execution: \"wallpaper.ps1\"","log.target":"openbas_implant::handle::handle_file","log.module_path":"openbas_implant::handle::handle_file","log.file":"src\\handle\\handle_file.rs","log.line":18},"target":"openbas_implant::handle::handle_file"}
{"timestamp":"2024-11-20T11:07:33.359553Z","level":"INFO","fields":{"message":"file execution execution stdout: \"\"","log.target":"openbas_implant::handle::handle_execution","log.module_path":"openbas_implant::handle::handle_execution","log.file":"src\\handle\\handle_execution.rs","log.line":18},"target":"openbas_implant::handle::handle_execution"}
{"timestamp":"2024-11-20T11:07:33.359573Z","level":"INFO","fields":{"message":"file execution execution stderr: \"\"","log.target":"openbas_implant::handle::handle_execution","log.module_path":"openbas_implant::handle::handle_execution","log.file":"src\\handle\\handle_execution.rs","log.line":19},"target":"openbas_implant::handle::handle_execution"}
```

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Handle errors for executable payload like command line payload

### Related issues

* Closes #1897 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality

### Further comments

This PR is linked with an implant PR

### CODE REVIEW

**Review by RomuDeuxfois — APPROVED** [review]

File: openbas-model/src/main/java/io/openbas/database/model/Executable.java [hunk 1]
```diff
@@ -40,4 +40,12 @@ public Executable() {}
   public Executable(String id, String type, String name) {
     super(id, type, name);
   }
+
+  /*
+   * return the number of actions a given payload is expected to achieve
+   * by default this is 2 here, one file drop and one execution
+   */
+  public int getNumberOfActions() {
+    return 2;
```
Comment (isselparra) [inline openbas-model/src/main/java/io/openbas/database/model/Executable.java:49]: **thought:** this `2` can be considered a [magic number](https://stackoverflow.com/a/47902), a number that it is used directly in the code. 

to improve readability, one can introduce a constant, for example:
```
public static final int NUMBER_OF_ACTIONS_TO_ACHIEVE_BY_DEFAULT = 2;
```
or
```
public static final int DEFAULT_NUMBER_OF_ACTIONS_TO_ACHIEVE = 2;
```

```suggestion
  public int getNumberOfActions() {
    return DEFAULT_NUMBER_OF_ACTIONS_TO_ACHIEVE;
```

just to let you know that :)

Comment (damgouj) [reply openbas-model/src/main/java/io/openbas/database/model/Executable.java:49]: Thanks ! I fix it !
