### PR TITLE
[backend/frontend] Add challenge preview for scenarios (#2985)

### LINKED ISSUE #2985: challenge preview is not working
## Description

Can't preview my challenge pages when I click on the eye icon

Image

What I see
Image

## Reproducible Steps

go to https://prerelease.obas.staging.filigran.io/admin/scenarios/7146b30c-0bc5-47e4-ae74-c68710f3051b/definition
 
click on the eye icon next to challenges

### PR DESCRIPTION
**Pull request by johanah29**
Closes #2985 

### Checklist

- [x] Add necessary api endpoints for challenges in scenarios
- [x] Reorganize actions files for challenges and documents
- [x] Move the challenge preview file to admin context
- [x] Update the challenge preview file according to our technical guidelines
- [x] Add the scenario context to the preview (finalize the feature)

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/rest/exercise/SimulationChallengesApi.java [hunk 1]
```diff
@@ -0,0 +1,124 @@
...
+import org.springframework.web.bind.annotation.GetMapping;
+import org.springframework.web.bind.annotation.PathVariable;
+import org.springframework.web.bind.annotation.RequestParam;
+import org.springframework.web.bind.annotation.RestController;
+
+@RestController
+@RequiredArgsConstructor
+public class SimulationChallengesApi extends RestBehavior {
+
+  private ExerciseRepository exerciseRepository;
```
Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/rest/exercise/SimulationChallengesApi.java:32]: you could make like l35

File: openbas-api/src/main/java/io/openbas/rest/exercise/SimulationChallengesApi.java [hunk 2]
```diff
@@ -0,0 +1,124 @@
...
+  public void setExerciseRepository(ExerciseRepository exerciseRepository) {
+    this.exerciseRepository = exerciseRepository;
+  }
+
+  @Autowired
+  public void setUserRepository(UserRepository userRepository) {
+    this.userRepository = userRepository;
+  }
+
+  private List<Document> getPlayerDocuments(List<Article> articles, List<Inject> injects) {
```
Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/rest/exercise/SimulationChallengesApi.java:52]: Maybe you could relocate this function to a service layer?

File: openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeApi.java [hunk 3]
```diff
@@ -150,7 +126,7 @@ public ChallengeResult tryChallenge(
 
   @PostMapping("/api/player/challenges/{exerciseId}/{challengeId}/validate")
   @Transactional(rollbackOn = Exception.class)
-  public ChallengesReader validateChallenge(
+  public SimulationChallengesReader validateChallenge(
```
Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/rest/challenge/ChallengeApi.java:129]: Maybe you could relocate this code to SimulationChallengesApi

File: openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioChallengesApi.java [hunk 4]
```diff
@@ -0,0 +1,123 @@
...
+  public void setUserRepository(UserRepository userRepository) {
+    this.userRepository = userRepository;
+  }
+
+  @Autowired
+  public void setScenarioRepository(ScenarioRepository scenarioRepository) {
+    this.scenarioRepository = scenarioRepository;
+  }
+
+  private List<Document> getPlayerDocuments(List<Article> articles, List<Inject> injects) {
```
Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioChallengesApi.java:52]: Is this the same function as in SimulationchallengeApi?

File: openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioChallengesApi.java [hunk 5]
```diff
@@ -0,0 +1,123 @@
...
+@RequiredArgsConstructor
+public class ScenarioChallengesApi extends RestBehavior {
+
+  private ScenarioRepository scenarioRepository;
+  private UserRepository userRepository;
+  private ChallengeRepository challengeRepository;
+  private final ChallengeService challengeService;
+
+  @Autowired
+  public void setChallengeRepository(ChallengeRepository challengeRepository) {
```
Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/rest/scenario/ScenarioChallengesApi.java:38]: Same as in SimualtionchhalengeApi: you could use private final ..

File: openbas-front/src/admin/components/common/articles/ArticleAddDocuments.js [hunk 6]
```diff
@@ -17,7 +17,7 @@ import * as R from 'ramda';
 import { useContext, useState } from 'react';
 import { makeStyles } from 'tss-react/mui';
 
-import { fetchDocuments } from '../../../../actions/Document';
+import { fetchDocuments } from '../../../../actions/Document.js';
```
Comment (savacano28) [inline openbas-front/src/admin/components/common/articles/ArticleAddDocuments.js:20]: Doument.js was deleted, no? check this import :)

File: openbas-front/src/admin/components/common/articles/ArticleForm.js [hunk 7]
```diff
@@ -7,7 +7,7 @@ import { useDispatch } from 'react-redux';
 import { makeStyles } from 'tss-react/mui';
 
 import { fetchChannels } from '../../../../actions/channels/channel-action';
-import { fetchDocuments } from '../../../../actions/Document';
+import { fetchDocuments } from '../../../../actions/Document.js';
```
Comment (savacano28) [inline openbas-front/src/admin/components/common/articles/ArticleForm.js:10]: Same as ArticleAddDocuments

File: openbas-front/src/admin/components/common/injects/form/InjectDefinition.js
Comment (savacano28) [inline openbas-front/src/admin/components/common/injects/form/InjectDefinition.js:1]: empty file

File: openbas-front/src/admin/components/components/challenges/ChallengeForm.js [hunk 8]
```diff
@@ -7,7 +7,7 @@ import { FieldArray } from 'react-final-form-arrays';
 import { useDispatch } from 'react-redux';
 import { makeStyles } from 'tss-react/mui';
 
-import { fetchDocuments } from '../../../../actions/Document';
+import { fetchDocuments } from '../../../../actions/Document.js';
```
Comment (savacano28) [inline openbas-front/src/admin/components/components/challenges/ChallengeForm.js:10]: To check Import

**Comment by savacano28** [comment]
Tests:
1. Preview on definition (simualtion/sceanrio) : OK
image

2. Link with the challenge link in email: NOK ( I do not have access )
image

File: openbas-front/src/public/components/challenges/Challenges.js [hunk 9]
```diff
@@ -1,12 +1,6 @@
-import { useQueryParameter } from '../../../utils/Environment';
 import ChallengesPlayer from './ChallengesPlayer';
-import ChallengesPreview from './ChallengesPreview';
 
 const Challenges = () => {
```
Comment (savacano28) [inline openbas-front/src/public/components/challenges/Challenges.js:3]: Maybe we dont need this file anymore?

**Comment by MarineLeM** [comment]
I have access to the challenge preview page, but I encountered an issue when clicking the 'Back to Administration' button. The redirection URL is incorrect, which results in the scenario page's definition tab not displaying properly.
image

**Comment by MarineLeM** [comment]
When you are in Player mode the simulation title is no longer displayed...
image

File: openbas-front/src/admin/components/common/challenges/ChallengesPreview.tsx [hunk 10]
```diff
@@ -0,0 +1,227 @@
...
+    return (
+      <div className={classes.root}>
+        {permissions.isLoggedIn && permissions.canRead && !R.isEmpty(value.linkToPlayerMode) && (
+          <Button
+            color="secondary"
+            variant="outlined"
+            component={Link}
+            to={value.linkToPlayerMode}
+            style={{
+              position: 'absolute',
```
Comment (MarineLeM) [inline openbas-front/src/admin/components/common/challenges/ChallengesPreview.tsx:90]: Please avoid using 'position: absolute' unless it is absolutely necessary, and i think it's not required in this case.

File: openbas-front/src/admin/components/common/challenges/ChallengesPreview.tsx [hunk 11]
```diff
@@ -0,0 +1,227 @@
...
+          </Button>
+        )}
+        {permissions.isLoggedIn && permissions.canRead && (
+          <Button
+            color="primary"
+            variant="outlined"
+            component={Link}
+            to={value.linkToAdministrationMode}
+            style={{
+              position: 'absolute',
```
Comment (MarineLeM) [inline openbas-front/src/admin/components/common/challenges/ChallengesPreview.tsx:105]: same

File: openbas-front/src/admin/components/common/challenges/ChallengesPreview.tsx [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+
+const useStyles = makeStyles()(theme => ({
+  root: {
+    position: 'relative',
+    flexGrow: 1,
+    padding: theme.spacing(2),
+  },
+  logo: {
+    width: 100,
+    margin: '0px 0px 10px 0px',
```
Comment (MarineLeM) [inline openbas-front/src/admin/components/common/challenges/ChallengesPreview.tsx:33]: use theme.spacing please :)

**Comment by MarineLeM** [comment]
1- When you are in preview mode from a simulation, clicking 'Switch to Player Mode' redirects you to the URL 'challenges/:id?challenge=null&user=null&preview=false'. If you refresh the page from this point, you encounter an infinite loading issue.
image

Redirecting to the public URL may not be the best solution because refreshing the page causes you to lose context, preventing you from navigating back to the admin mode.


2- When you are in preview mode from a simulation, if you click 'Switch to Player Mode', then select a challenge and submit the correct flag, an unexpected behavior occurs.
The system is intended to inform users of a correct flag submission within the Challenge Modal, and the icon on the Challenge Card should turn green to reflect this."
As you can see in this screenshot : 
image

Or you can see it here https://testing.obas.staging.filigran.io/challenges/eb8bf463-dd46-42a9-991e-f764bc3924d0?challenge=null&user=null&preview=false

File: openbas-front/src/actions/Challenge.ts [hunk 13]
```diff
@@ -0,0 +1,70 @@
...
+};
+
+export const updateChallenge = (challengeId: string, data: ChallengeInput) => (dispatch: Dispatch) => {
+  const uri = `/api/challenges/${challengeId}`;
+  return putReferential(challenge, uri, data)(dispatch);
+};
+
+export const addChallenge = (data: ChallengeInput) => (dispatch: Dispatch) => postReferential(challenge, '/api/challenges', data)(dispatch);
+
+export const tryChallenge = (challengeId: string, data: ChallengeTryInput) => (dispatch: Dispatch) => postReferential(null, `/api/challenges/${challengeId}/try`, data)(dispatch);
```
Comment (MarineLeM) [inline openbas-front/src/actions/Challenge.ts:37]: Since you set the schema to null in the postReferential function, you can simply use simplePostCall instead.
