### PR TITLE
[backend] Fix on deleted injector contract

### LINKED ISSUE #2203: Deleting a type representation in a mapper delete the injector contract
## Description

When deleting a type representation in a created mapper, it deletes the injector contract.

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a mapper. Save it.
2. Delete one of the representation type.
3. The injector contract has been deleted.

## Expected Output

The injector contract should not be deleted.

## Actual Output

The injector contract has been deleted.

### PR DESCRIPTION
**Pull request by Dimfacion**
### Proposed changes

* Better definition of relationship between injector contract and importer
*

### Related issues

* Closes #2203 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

**Review by savacano28 — DISMISSED** [review]

File: openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+@Component
+public class V3_60__Alter_xls_mapper_table extends BaseJavaMigration {
+
+  @Override
+  public void migrate(Context context) throws Exception {
+    Connection connection = context.getConnection();
+    Statement statement = connection.createStatement();
+
+    statement.execute(
+        "ALTER TABLE inject_importers alter column importer_mapper_id drop not null;");
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java:18]: The column is on the import_mappers table

File: openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java [hunk 2]
```diff
@@ -0,0 +1,24 @@
...
+    statement.execute(
+        "ALTER TABLE inject_importers alter column importer_injector_contract_id drop not null;");
+    statement.execute(
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java:21]: Same here

File: openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java (hunk 1 above)
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java:18]: The column name is different in SQL side and Java side

Comment (RomuDeuxfois) [reply openbas-api/src/main/java/io/openbas/migration/V3_60__Alter_xls_mapper_table.java:18]: NOP, I misunderstood

**Review by RomuDeuxfois — APPROVED** [review]

**Review by savacano28 — APPROVED** [review]
