### PR TITLE
[backend] Include payload tags in scenario export bundle (#3641)

### LINKED ISSUE #3645: Scenario export function does not include payload tags
## Description

Exporting a scenario with OpenBAS Implant contract injects (payloads) does not export the tags that are only referenced on Payloads. The resulting bundle is missing those tags while they are still referenced by the payloads serialisation.

## Environment

1. OS (where OpenBAS server runs): { e.g. Mac OS 10, Windows 10, Ubuntu 16.4, etc. }
2. OpenBAS version: { e.g. OpenBAS 1.0.2 }
3. OpenBAS client: { e.g. frontend or python }
4. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a scenario, add injects with a payload
2. Set a tag on the payload thta only exists on that payload (do not place that tag anywhere else)
3. Export scenario
4. Import scenario on a different instance => crash

## Expected Output

Payload tags should be included in export bundle

## Actual Output

Payload tags are ignored in the scenario export bundle.

### PR DESCRIPTION
**Pull request by antoinemzs**
### Proposed changes

* Include payload tags in scenario export bundle

### Testing Instructions

1. Step-by-step how to test
2. Environment or config notes

### Related issues

* Related #3641
* Closes #3645 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/service/ScenarioService.java [hunk 1]
```diff
@@ -456,8 +456,20 @@ public void exportScenario(
     // Add Injects
     objectMapper.addMixIn(Inject.class, Mixins.Inject.class);
     scenarioFileExport.setInjects(scenario.getInjects());
-    scenarioTags.addAll(
-        scenario.getInjects().stream().flatMap(inject -> inject.getTags().stream()).toList());
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/service/ScenarioService.java:460]: Did you face any issues on using direclty getTags() instead of .getTags().stream()).toList() ?
I am worried

Comment (antoinemzs) [reply openbas-api/src/main/java/io/openbas/service/ScenarioService.java:460]: That's how it's done e.g. in the Exercise export. PersistentBag is an implementation of a List. What sorts of issues do you expect?

FWIW there's a test that runs this code.
