### PR TITLE
[frontend] Fix traduction for endpoint list

### LINKED ISSUE #2822: Text layout issue in endpoints list
## Description

Missing some spaces:

Image

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

* Fix traduction spaces
*

### Related issues

* Closes #2822 
*

### Checklist

- [x] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx [hunk 1]
```diff
@@ -276,7 +276,10 @@ const Endpoints = () => {
         <a href={`${settings.platform_base_url}/admin/agents`} target="_blank" rel="noopener noreferrer">
           {t('agent installation page')}
         </a>
-        {t(' and in our ')}
+        &nbsp;
+        {' '}
```
Comment (impolitepanda) [inline openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx:280]: question: out of curiosity, what is the reason in adding this line after an nbsp ?

Comment (savacano28) [reply openbas-front/src/admin/components/assets/endpoints/Endpoints.tsx:280]: Thanks!! It was the linter!! I'll fix it!
