### PR TITLE
[frontend/backend] fix contract based features using key instead of type

### LINKED ISSUE #2529: Inject creation form field is based on key rather than on type
## Description

My fields:

Image

Display:

Image

Despite the fact my field is of type "asset", I've a text field instead of the list of assets.

### PR DESCRIPTION
**Pull request by guillaumejparis**
### Proposed changes

*
*

### Related issues

* Closes #2529 
*

### Checklist

- [ ] I consider the submitted work as finished
- [ ] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-api/src/test/java/io/openbas/rest/inject_expectation/InjectExpectationServiceTest.java [hunk 1]
```diff
@@ -43,9 +44,15 @@ class InjectExpectationServiceTest extends IntegrationTest {
...
...\":\"Object\",\"cardinality\":\"1\",\"children\":[{\"key\":\"exercise.id\",\"label\":\"Id of the exercise in the platform\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]},{\"key\":\"exercise.name\",\"label\":\"Name of the exercise\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]},{\"key\":\"exercise.description\",\"label\":\"Description of the exercise\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]}]},{\"key\":\"teams\",\"label\":\"List of team name for the injection\",\"type\":\"String\",\"cardinality\":\"n\",\"children\":[]},{\"key\":\"player_uri\",\"label\":\"Player interface platform link\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]},{\"key\":\"challenges_uri\",\"label\":\"Challenges interface platform link\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]},{\"key\":\"scoreboard_uri\",\"label\":\"Scoreboard interface platform link\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]},{\"key\":\"lessons_uri\",\"label\":\"Lessons learned interface platform link\",\"type\":\"String\",\"cardinality\":\"1\",\"children\":[]}],\"contract_attack_patterns_external_ids\":[],\"is_atomic_testing\":true,\"platforms\":[]}");
```
Comment (guillaumejparis) [inline openbas-api/src/test/java/io/openbas/rest/inject_expectation/InjectExpectationServiceTest.java:55]:
```suggestion
```

**Review by Dimfacion — APPROVED** [review]
