### PR TITLE
[backend/frontend] Fix partial delete of documents (#3467)

### LINKED ISSUE #3467: Partial delete + error when deleting a file associated to a payload
## Description

Partial delete + error when deleting a file associated to a payload.

1. Create a payload of type "file drop"
2. Upload a new document as part of this payload
3. Try to delete the document

=> An error occured.

But, actually, the document was deleted in Minio (S3) but not the database entry. Which lead to an very inconsistant and not usable behavior.

What we should do:

1. A document associated to at least 1 payload cannot be deleted
2. When it is not associated to any payload it can be deleted
3. We should have a popover + dialog to display "where the file is used"

Like this:

Image

When clicking on number:

Image

### PR DESCRIPTION
**Pull request by savacano28**
### Proposed changes

Frontend
* Remove underline in ContextLink componsant
* Update composant DialogDeleteDocument

Backend
* Fetch list of entities related to document and show them in the delete dialog
* If user click on delete -> Document and all the relations are deleted too

image

### Testing Instructions

1. Add a document
2. Related this document to any channle, challenge. paylaod, inject
3.  Try delete the document
4. Check behavior: Force delete (document is still referenced in other entities) (was ok, or any backend error?)
5. Check minio (:10001)

### Related issues

* Closes #3467 
*

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [x] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [x] Where necessary I refactored code to improve the overall quality
- [x] For bug fix -> I implemented a test that covers the bug

### Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/migration/V4_10__Update_contrainst_documents.java [hunk 1]
```diff
@@ -0,0 +1,34 @@
...
+  public void migrate(Context context) throws Exception {
+    try (Statement stmt = context.getConnection().createStatement()) {
+
+      // Drop and recreate foreign key in scenarios_documents
+      stmt.execute(
+          """
+                ALTER TABLE scenarios_documents
+                DROP CONSTRAINT document_id_fk,
+                ADD CONSTRAINT document_id_fk
+                FOREIGN KEY (document_id) REFERENCES documents(document_id) ON DELETE CASCADE
```
Comment (antoinemzs) [inline openbas-api/src/main/java/io/openbas/migration/V4_10__Update_contrainst_documents.java]: ok this adds the ON DELETE CASCADE clause, it wasn't obvious. :+1:

File: openbas-api/src/main/java/io/openbas/rest/document/DocumentApi.java [hunk 2]
```diff
@@ -484,19 +492,35 @@ private List<Document> getScenarioPlayerDocuments(Scenario scenario) {
...
+            toOutputWithContext(
+                documentDeleteRepository.findSimulationArticlesByDocument(documentId)))
+        .atomicTestings(toOutput(documentDeleteRepository.findAtomicTestingsByDocument(documentId)))
+        .scenarioInjects(
+            toOutputWithContext(documentDeleteRepository.findScenarioInjectsByDocument(documentId)))
+        .simulationInjects(
+            toOutputWithContext(
+                documentDeleteRepository.findSimulationInjectsByDocument(documentId)))
+        .challenges(toOutput(documentDeleteRepository.findChallengesByDocument(documentId)))
+        .build();
```
Comment (antoinemzs) [inline openbas-api/src/main/java/io/openbas/rest/document/DocumentApi.java]: Perhaps all repository calls should live on a service layer

Comment (savacano28) [reply openbas-api/src/main/java/io/openbas/rest/document/DocumentApi.java]: yes, I'm changing this part :)

**Comment by antoinemzs** [comment]
Is there a reason why the relationships are not part of the data model and thus not collectable via property access, rather than specialised native SQL queries ?

File: openbas-front/src/admin/components/components/documents/DocumentPopover.js [hunk 3]
```diff
@@ -172,26 +282,13 @@ const DocumentPopover = (props) => {
...
-            {t('Cancel')}
-          </Button>
-          <Button color="secondary" onClick={submitDelete}>
-            {t('Delete')}
-          </Button>
-        </DialogActions>
-      </Dialog>
+        handleClose={handleCloseDelete}
+        handleSubmit={submitDelete}
+        text={renderDialogText()}
```
Comment (antoinemzs) [inline openbas-front/src/admin/components/components/documents/DocumentPopover.js]: Passing complex controls in this prop ends up nesting them inside a https://mui.com/material-ui/api/dialog-content-text/ (see the implementation for `DialogDelete`) and causes html syntax errors, possible visual artifacts.

Consider adding a prop for non-text contents

**Review by antoinemzs — APPROVED** [review]
