### PR TITLE
[backend] Fix Crowdstrike agent registered

### LINKED ISSUE #2672: CrowdStrike executor is broken in an instance, with a stack trace preventing it to run properly
## Description

In the instance https://filigran.obas.filigran.io/.

```
{"sequenceNumber":0,"timestamp":1742033489785,"nanoseconds":785511673,"level":"ERROR","threadName":"ThreadPoolTaskScheduler4","loggerName":"org.springframework.scheduling.support.TaskUtils$LoggingErrorHandler","context":{"name":"default","birthdate":1742027435231,"properties":{}},"mdc": {},"message":"Unexpected error occurred in scheduled task","throwable":{"className":"org.springframework.dao.IncorrectResultSizeDataAccessException","message":"Query did not return a unique result: 2 results were returned","stepArray":[{"className":"org.springframework.orm.jpa.vendor.HibernateJpaDialect","methodName":"convertHibernateAccessException","fileName":"HibernateJpaDialect.java","lineNumber":301},{"className":"org.springframework.orm.jpa.vendor.HibernateJpaDialect","methodName":"translateExceptionIfPossible","fileName":"HibernateJpaDialect.java","lineNumber":244},{"className":"org.springframework.orm.jpa.AbstractEntityManagerFactoryBean","methodName":"translateExceptionIfPossible","fileName":"AbstractEntityManagerFactoryBean.java","lineNumber":550},{"className":"org.springframework.dao.support.ChainedPersistenceExceptionTranslator","methodName":"translateExceptionIfPossible","fileName":"ChainedPersistenceExceptionTranslator.java","lineNumber":61},{"className":"org.springframework.dao.support.DataAccessUtils","methodName":"translateIfNecessary","fileName":"DataAccessUtils.java","lineNumber":335},{"className":"org.springframework.dao.support.PersistenceExceptionTranslationInterceptor","methodName":"invoke","fileName":"PersistenceExceptionTranslationInterceptor.java","lineNumber":160},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","methodName":"proceed","fileName":"ReflectiveMethodInvocation.java","lineNumber":184},{"className":"org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor","methodName":"invoke","fileName":"CrudMethodMetadataPostProcessor.java","lineNumber":136},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","methodName":"proceed","fileName":"ReflectiveMethodInvocation.java","lineNumber":184},{"className":"org.springframework.aop.interceptor.ExposeInvocationInterceptor","methodName":"invoke","fileName":"ExposeInvocationInterceptor.java","lineNumber":97},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","methodName":"proceed","fileName":"ReflectiveMethodInvocation.java","lineNumber":184},{"className":"org.springframework.aop.framework.JdkDynamicAopProxy","methodName":"invoke","fileName":"JdkDynamicAopProxy.java","lineNumber":223},{"className":"jdk.proxy2.$Proxy237","methodName":"findByAtleastOneMacAddress","fileName":"null","lineNumber":-1},{"className":"io.openbas.service.EndpointService","methodName":"findEndpointByAtLeastOneMacAddress","fileName":"EndpointService.java","lineNumber":106},{"className":"io.openbas.service.EndpointService","methodName":"registerAgentEndpoint","fileName":"EndpointService.java","lineNumber":162},{"className":"io.openbas.executors.crowdstrike.service.CrowdStrikeExecutorService","methodName":"run","fileName":"CrowdStrikeExecutorService.java","lineNumber":96},{"className":"org.springframework.scheduling.support.DelegatingErrorHandlingRunnable","methodName":"run","fileName":"DelegatingErrorHandlingRunnable.java","lineNumber":54},{"className":"java.util.concurrent.Executors$RunnableAdapter","methodName":"call","fileName":"null","lineNumber":-1},{"className":"java.util.concurrent.FutureTask","methodName":"runAndReset","fileName":"null","lineNumber":-1},{"className":"java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask","methodName":"run","fileName":"null","lineNumber":-1},{"className":"java.util.concurrent.ThreadPoolExecutor","methodName":"runWorker","fileName":"null","lineNumber":-1},{"className":"java.util.concurrent.ThreadPoolExecutor$Worker","methodName":"run","fileName":"null","lineNumber":-1},{"className":"java.lang.Thread","methodName":"run","fileName":"null","lineNumber":-1}],"cause":{"className":"org.hibernate.NonUniqueResultException","message":"Query did not return a unique result: 2 results were returned","stepArray":[{"className":"org.hibernate.query.spi.AbstractSelectionQuery","methodName":"uniqueElement","fileName":"AbstractSelectionQuery.java","lineNumber":578},{"className":"org.hibernate.query.spi.AbstractSelectionQuery","methodName":"getSingleResult","fileName":"AbstractSelectionQuery.java","lineNumber":561},{"className":"jdk.internal.reflect.DirectMethodHandleAccessor","methodName":"invoke","fileName":"null","lineNumber":-1},{"className":"java.lang.reflect.Method","methodName":"invoke","fileName":"null","lineNumber":-1},{"className":"org.springframework.orm.jpa.SharedEntityManagerCreator$DeferredQueryInvocationHandler","methodName":"invoke","fileName":"SharedEntityManagerCreator.java","lineNumber":418},{"className":"jdk.proxy2.$Proxy296","methodName":"getSingleResult","fileName":"null","lineNumber":-1},{"className":"org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution","methodName":"doExecute","fileName":"JpaQueryExecution.java","lineNumber":224},{"className":"org.springframework.data.jpa.repository.query.JpaQueryExecution","methodName":"execute","fileName":"JpaQueryExecution.java","lineNumber":93},{"className":"org.springframework.data.jpa.repository.query.AbstractJpaQuery","methodName":"doExecute","fileName":"AbstractJpaQuery.java","lineNumber":152},{"className":"org.springframework.data.jpa.repository.query.AbstractJpaQuery","methodName":"execute","fileName":"AbstractJpaQuery.java","lineNumber":140},{"className":"org.springframework.data.repository.core.support.RepositoryMethodInvoker","methodName":"doInvoke","fileName":"RepositoryMethodInvoker.java","lineNumber":170},{"className":"org.springframework.data.repository.core.support.RepositoryMethodInvoker","methodName":"invoke","fileName":"RepositoryMethodInvoker.java","lineNumber":158},{"className":"org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor","methodName":"doInvoke","fileName":"QueryExecutorMethodInterceptor.java","lineNumber":169},{"className":"org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor","methodName":"invoke","fileName":"QueryExecutorMethodInterceptor.java","lineNumber":148},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","methodName":"proceed","fileName":"ReflectiveMethodInvocation.java","lineNumber":184},{"className":"org.springframework.transaction.interceptor.TransactionAspectSupport","methodName":"invokeWithinTransaction","fileName":"TransactionAspectSupport.java","lineNumber":379},{"className":"org.springframework.transaction.interceptor.TransactionInterceptor","methodName":"invoke","fileName":"TransactionInterceptor.java","lineNumber":119},{"className":"org.springframework.aop.framework.ReflectiveMethodInvocation","methodName":"proceed","fileName":"ReflectiveMethodInvocation.java","lineNumber":184},{"className":"org.springframework.dao.support.PersistenceExceptionTranslationInterceptor","methodName":"invoke","fileName":"PersistenceExceptionTranslationInterceptor.java","lineNumber":138}],"commonFramesCount":17}}}
```

### PR DESCRIPTION
**Pull request by damgouj**
### Proposed changes

* Manage register for multiple endpoints with same mac address
* Add limit for Crowdstrike API (issue will be created to improve the limit)

### Related issues

* Closes #2672 

### Checklist

- [x] I consider the submitted work as finished
- [x] I tested the code for its functionality
- [ ] I wrote test cases for the relevant uses case
- [ ] I added/update the relevant documentation (either on github or on notion)
- [ ] Where necessary I refactored code to improve the overall quality
- [ ] For bug fix -> I implemented a test that covers the bug

### CODE REVIEW

File: openbas-api/src/main/java/io/openbas/executors/crowdstrike/client/CrowdStrikeExecutorClient.java [hunk 1]
```diff
@@ -53,7 +53,8 @@ public class CrowdStrikeExecutorClient {
 
   public ResourcesHosts devices() {
     try {
-      String jsonResponse = this.get(ENDPOINTS_URI + "?id=" + this.config.getHostGroup());
+      String jsonResponse =
+          this.get(ENDPOINTS_URI + "?id=" + this.config.getHostGroup() + "&limit=5000");
```
Comment (RomuDeuxfois) [inline openbas-api/src/main/java/io/openbas/executors/crowdstrike/client/CrowdStrikeExecutorClient.java:57]: Crowdstrike has an Hard limit on endpoints ?

File: openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java [hunk 2]
```diff
@@ -39,9 +38,9 @@ List<Endpoint> findByHostnameAndAtleastOneIp(
 
   @Query(
       value =
-          "select e.* from assets e where e.endpoint_mac_addresses && cast(:macAddresses as text[])",
+          "select e.* from assets e where e.endpoint_mac_addresses && cast(:macAddresses as text[]) order by e.asset_id",
```
Comment (RomuDeuxfois) [inline openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java:41]: Can we order by first update to be consistent with new one or not ?

File: openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorService.java [hunk 3]
```diff
@@ -91,7 +91,10 @@ public CrowdStrikeExecutorService(
   @Override
   public void run() {
     log.info("Running CrowdStrike executor endpoints gathering...");
-    List<CrowdStrikeDevice> devices = this.client.devices().getResources().stream().toList();
+    List<CrowdStrikeDevice> devices =
```
Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorService.java:94]: List<CrowdStrikeDevice> devices = this.client.devices().getResources().stream()
    .filter(device -> device.getHostname() != null)
    .collect(Collectors.toList());

Comment (savacano28) [inline openbas-api/src/main/java/io/openbas/executors/crowdstrike/service/CrowdStrikeExecutorService.java:94]: List<CrowdStrikeDevice> devices = this.client.devices().getResources().stream()
    .filter(device -> device.getHostname() != null)
    .collect(Collectors.toList());

File: openbas-api/src/main/java/io/openbas/executors/crowdstrike/client/CrowdStrikeExecutorClient.java (hunk 1 above)
Comment (damgouj) [reply openbas-api/src/main/java/io/openbas/executors/crowdstrike/client/CrowdStrikeExecutorClient.java:57]: Yes, I am going to create an issue because we need to update this code to manage more than 5000 Crowdstrike agents (with the pagination from their API https://www.falconpy.io/Service-Collections/Host-Group.html?highlight=%2Fdevices%2Fcombin#querycombinedgroupmembers)

File: openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java (hunk 2 above)
Comment (damgouj) [reply openbas-model/src/main/java/io/openbas/database/repository/EndpointRepository.java:41]: I don't know how to do that and if we can "trust" the creation or update date so I decided to order by asset to always get the same

**Review by RomuDeuxfois — APPROVED** [review]
